services:
  pgsql:
    POSTGRES_USER: pguser
    POSTGRES_PASSWORD: pgpassword
    POSTGRES_DB: db_enquetes
    image: postgres:latest
    ports:
      - '5433:5432'
    container_name: 'pgsql'
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg-data:
